[keyboard]
name = "smartremote"
product_name = "smartremote"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P0_20", "P0_22", "P0_24"]
col_pins = ["P1_11", "P0_10", "P0_09"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 3
cols = 3
layers = 4 # 修改：已调整为 4 层

# Layer 0: 基础媒体层（灯灭）
# Layer 1: 鼠标与导航层（TT长按/连击进入，灯常亮）
# Layer 2: 网页与翻页层（TT长按/连击进入，灯呼吸）
# Layer 3: 终极Fn层/一键回家（单点任何层的第9键，快闪3下回家，灯灭）
keymap = [
    # ------------------ LAYER 0 (基础媒体层) ------------------
    [
        ["AudioVolUp",   "AudioVolDown",   "Right"],
        ["MouseWheelUp",    "Left", "MouseWheelDown"],
        ["PageUp",       "TT(1)",       "PageDown"], # 第9键：长按或连击3下进 Layer 1
    ],

    # ------------------ LAYER 1 (鼠标导航层) ------------------
    [
        ["MouseWheelUp",   "Up",           "MouseWheelDown"],
        ["Left",           "MouseBtnLeft", "Right"],
        ["_",              "TT(2)",         "Down"], # 第9键：长按或连击3下进 Layer 2
    ],

    # ------------------ LAYER 2 (网页办公层) ------------------
    [
        ["F5",             "Ctrl + W",     "Ctrl + T"], # 刷新、关标签、开标签
        ["Ctrl + Z",       "Ctrl + C",     "Ctrl + V"], # 撤销、复制、粘贴
        ["Home",           "TT(3)",          "End"], # 第9键：长按或连击3下进 Layer 3
    ],

    # ------------------ LAYER 3 (终极安全层/一键回家) ------------------
    # 无论你在 1、2、3 哪一层，只要单点一下第9键，触发 TO(0) 即可瞬间回到基础层！
    [
        ["_",              "_",            "_"],
        ["_",              "_",            "_"],
        ["_",              "TO(0)",            "_"], # 第9键：一键重置，瞬间拔寨回营到 Layer 0
    ],
]

[behavior]
# 核心省电配置：60000 毫秒（60 秒）完全没有按键操作后，键盘自动进入深度休眠
async_idle_timeout = 60000

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false
